# Generated by Django 5.1 on 2024-08-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_managers_alter_customuser_email_and_more'),
        ('bookshelf', '0003_customuser'),
    ]

    operations = [
    ]
